# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mihir/Downloads/cs648-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mihir/Downloads/cs648-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihir/Downloads/cs648-project/CMakeFiles /home/mihir/Downloads/cs648-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihir/Downloads/cs648-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named implement

# Build rule for target.
implement: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 implement
.PHONY : implement

# fast build rule for target.
implement/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implement.dir/build.make CMakeFiles/implement.dir/build
.PHONY : implement/fast

#=============================================================================
# Target rules for targets named ALL_CGAL_TARGETS

# Build rule for target.
ALL_CGAL_TARGETS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ALL_CGAL_TARGETS
.PHONY : ALL_CGAL_TARGETS

# fast build rule for target.
ALL_CGAL_TARGETS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ALL_CGAL_TARGETS.dir/build.make CMakeFiles/ALL_CGAL_TARGETS.dir/build
.PHONY : ALL_CGAL_TARGETS/fast

#=============================================================================
# Target rules for targets named cgal_check_build_system

# Build rule for target.
cgal_check_build_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cgal_check_build_system
.PHONY : cgal_check_build_system

# fast build rule for target.
cgal_check_build_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgal_check_build_system.dir/build.make CMakeFiles/cgal_check_build_system.dir/build
.PHONY : cgal_check_build_system/fast

#=============================================================================
# Target rules for targets named implement2

# Build rule for target.
implement2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 implement2
.PHONY : implement2

# fast build rule for target.
implement2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implement2.dir/build.make CMakeFiles/implement2.dir/build
.PHONY : implement2/fast

#=============================================================================
# Target rules for targets named min_circle_2

# Build rule for target.
min_circle_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 min_circle_2
.PHONY : min_circle_2

# fast build rule for target.
min_circle_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min_circle_2.dir/build.make CMakeFiles/min_circle_2.dir/build
.PHONY : min_circle_2/fast

#=============================================================================
# Target rules for targets named on3

# Build rule for target.
on3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 on3
.PHONY : on3

# fast build rule for target.
on3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/on3.dir/build.make CMakeFiles/on3.dir/build
.PHONY : on3/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named timepass

# Build rule for target.
timepass: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timepass
.PHONY : timepass

# fast build rule for target.
timepass/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timepass.dir/build.make CMakeFiles/timepass.dir/build
.PHONY : timepass/fast

implement.o: implement.cpp.o
.PHONY : implement.o

# target to build an object file
implement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implement.dir/build.make CMakeFiles/implement.dir/implement.cpp.o
.PHONY : implement.cpp.o

implement.i: implement.cpp.i
.PHONY : implement.i

# target to preprocess a source file
implement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implement.dir/build.make CMakeFiles/implement.dir/implement.cpp.i
.PHONY : implement.cpp.i

implement.s: implement.cpp.s
.PHONY : implement.s

# target to generate assembly for a file
implement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implement.dir/build.make CMakeFiles/implement.dir/implement.cpp.s
.PHONY : implement.cpp.s

implement2.o: implement2.cpp.o
.PHONY : implement2.o

# target to build an object file
implement2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implement2.dir/build.make CMakeFiles/implement2.dir/implement2.cpp.o
.PHONY : implement2.cpp.o

implement2.i: implement2.cpp.i
.PHONY : implement2.i

# target to preprocess a source file
implement2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implement2.dir/build.make CMakeFiles/implement2.dir/implement2.cpp.i
.PHONY : implement2.cpp.i

implement2.s: implement2.cpp.s
.PHONY : implement2.s

# target to generate assembly for a file
implement2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implement2.dir/build.make CMakeFiles/implement2.dir/implement2.cpp.s
.PHONY : implement2.cpp.s

min_circle_2.o: min_circle_2.cpp.o
.PHONY : min_circle_2.o

# target to build an object file
min_circle_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min_circle_2.dir/build.make CMakeFiles/min_circle_2.dir/min_circle_2.cpp.o
.PHONY : min_circle_2.cpp.o

min_circle_2.i: min_circle_2.cpp.i
.PHONY : min_circle_2.i

# target to preprocess a source file
min_circle_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min_circle_2.dir/build.make CMakeFiles/min_circle_2.dir/min_circle_2.cpp.i
.PHONY : min_circle_2.cpp.i

min_circle_2.s: min_circle_2.cpp.s
.PHONY : min_circle_2.s

# target to generate assembly for a file
min_circle_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min_circle_2.dir/build.make CMakeFiles/min_circle_2.dir/min_circle_2.cpp.s
.PHONY : min_circle_2.cpp.s

on3.o: on3.cpp.o
.PHONY : on3.o

# target to build an object file
on3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/on3.dir/build.make CMakeFiles/on3.dir/on3.cpp.o
.PHONY : on3.cpp.o

on3.i: on3.cpp.i
.PHONY : on3.i

# target to preprocess a source file
on3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/on3.dir/build.make CMakeFiles/on3.dir/on3.cpp.i
.PHONY : on3.cpp.i

on3.s: on3.cpp.s
.PHONY : on3.s

# target to generate assembly for a file
on3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/on3.dir/build.make CMakeFiles/on3.dir/on3.cpp.s
.PHONY : on3.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.s
.PHONY : test.cpp.s

timepass.o: timepass.cpp.o
.PHONY : timepass.o

# target to build an object file
timepass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timepass.dir/build.make CMakeFiles/timepass.dir/timepass.cpp.o
.PHONY : timepass.cpp.o

timepass.i: timepass.cpp.i
.PHONY : timepass.i

# target to preprocess a source file
timepass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timepass.dir/build.make CMakeFiles/timepass.dir/timepass.cpp.i
.PHONY : timepass.cpp.i

timepass.s: timepass.cpp.s
.PHONY : timepass.s

# target to generate assembly for a file
timepass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timepass.dir/build.make CMakeFiles/timepass.dir/timepass.cpp.s
.PHONY : timepass.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ALL_CGAL_TARGETS"
	@echo "... cgal_check_build_system"
	@echo "... implement"
	@echo "... implement2"
	@echo "... min_circle_2"
	@echo "... on3"
	@echo "... test"
	@echo "... timepass"
	@echo "... implement.o"
	@echo "... implement.i"
	@echo "... implement.s"
	@echo "... implement2.o"
	@echo "... implement2.i"
	@echo "... implement2.s"
	@echo "... min_circle_2.o"
	@echo "... min_circle_2.i"
	@echo "... min_circle_2.s"
	@echo "... on3.o"
	@echo "... on3.i"
	@echo "... on3.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... timepass.o"
	@echo "... timepass.i"
	@echo "... timepass.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

